- hosts: nginx-01
  become: true
  vars:
    nginx_port: 8080

  tasks:

  - name: Add repository
    ansible.builtin.yum_repository:
      name: nginx-stable
      description: nginx stable repo
      baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck: yes
      state: present
      enabled: yes
      gpgkey: https://nginx.org/keys/nginx_signing.key
#      module_hotfixes: yes #не работает в версии ansible 2.10.8

  - name: Install NGINX
    yum:
      name: nginx
      state: present
    notify:
      - enable and start NGINX
     

  - name: Copy default.conf
    template:
      src: ../templates/default.conf.j2
      dest: /etc/nginx/conf.d/default.conf
    notify:
      - reload NGINX   

  handlers:

  - name: enable and start NGINX
    ansible.builtin.systemd:
      name: nginx
      enabled: yes
      state: started

  - name: reload NGINX
    ansible.builtin.systemd:
      name: nginx
      state: reloaded
